STUDENTS = [
    'alana',
    'ali',
    'alice',
    'alisha',
    'amanda',
    'armando',
    'bruno',
    'calla',
    'christine',
    'cyril',
    'daisy',
    'eddie',
    'elizabeth',
    'emmi',
    'hannah',
    'john',
    'jonah',
    'jose',
    'kristen',
    'liezl',
    'lukas',
    'marcial',
    'olivia',
    'reymundo',
    'samantha',
    'sanchya',
    'shira',
    'veronica',
    'wilfried',
    'william'
]

FULL_NAMES = {
    'alana': 'Alana Fallon',
    'ali': 'Alexandra Paul',
    'alice': 'TianYi Ma',
    'alisha': 'Alisha Saxena',
    'amanda': 'Amanda Glazer',
    'armando': 'Armando Gomez',
    'bruno': 'Bruno Lucarelli',
    'calla': 'Calla Carter',
    'christine': 'Christine Yang',
    'cyril': 'Cyril Caeser',
    'daisy': 'YueQi Zhang',
    'eddie': 'Eddie Dugan',
    'elizabeth': 'Elizabeth Smith',
    'emmi': 'Emilia Russo',
    'hannah': 'Hannah Zhang',
    'john': 'John Franklin',
    'jonah': 'Jonah Starling',
    'jose': 'Jose Guvenilir',
    'kristen': 'Kristen Gee',
    'liezl': 'Liezl Puzon',
    'lukas': 'Lukas Munoz',
    'marcial': 'Marcial Abrahantes',
    'olivia': 'Olivia Miller',
    'reymundo': 'Reymundo Cano',
    'samantha': 'Samantha Miller',
    'sanchya': 'Sanchya Mahajan',
    'shira': 'Shira Katz',
    'veronica': 'Veronica Gunn',
    'wilfried': 'Wilfried Hounyo',
    'william': 'William Lopez-Cordero'
}

SCHOOLS = {
    'alana': 'Cornell University',
    'ali': 'Brown University',
    'alice': 'Queen\'s University',
    'alisha': 'Massachusetts Institute of Technology',
    'amanda': 'Harvard University',
    'armando': 'University of Illinois at Urbana-Champaign',
    'bruno': 'Rutgers University',
    'calla': 'Bryn Mawr College',
    'christine': 'University of Texas at Austin',
    'cyril': 'Florida International University',
    'daisy': 'Vanderbilt University',
    'eddie': 'Rice University',
    'elizabeth': 'Santa Clara University',
    'emmi': 'University of Chicago',
    'hannah': 'University of Waterloo',
    'john': 'Northwestern University',
    'jonah': 'University of Kentucky',
    'jose': 'Rensselaer Polytechnic Institute',
    'kristen': 'University of Pennsylvania',
    'liezl': 'Stanford University',
    'lukas': 'Bucknell University',
    'marcial': 'University of Florida',
    'olivia': 'Michigan State University',
    'reymundo': 'Massachusetts Institute of Technology',
    'samantha': 'University of Texas at Austin',
    'sanchya': 'University of Washington',
    'shira': 'University of Rochester',
    'veronica': 'University of Texas at Austin',
    'wilfried': 'Rochester Institute of Technology',
    'william': 'Massachusetts Institute of Technology'
}

PHOTOS = {
    'alana': 'alana.jpg',
    'ali': 'ali.jpg',
    'alice': 'alice.jpg',
    'alisha': 'anonymous.png',
    'amanda': 'amanda.jpg',
    'armando': 'armando.jpg',
    'bruno': 'bruno.jpg',
    'calla': 'anonymous.png',
    'christine': 'christine.jpg',
    'cyril': 'cyril.jpg',
    'daisy': 'daisy.jpg',
    'eddie': 'eddie.jpg',
    'elizabeth': 'elizabeth.jpg',
    'emmi': 'emmi.jpg',
    'hannah': 'hannah.jpg',
    'john': 'john.jpg',
    'jonah': 'jonah.jpg',
    'jose': 'jose.jpg',
    'kristen': 'kristen.jpg',
    'liezl': 'liezl.jpg',
    'lukas': 'anonymous.png',
    'marcial': 'anonymous.png',
    'olivia': 'olivia.jpg',
    'reymundo': 'reymundo.jpg',
    'samantha': 'samantha.jpg',
    'sanchya': 'sanchya.jpg',
    'shira': 'shira.jpg',
    'veronica': 'veronica.jpg',
    'wilfried': 'wilfried.jpg',
    'william': 'william.jpg'
}
